### ISSUE TITLE
Refresh from armory error

### ISSUE THREAD

**Issue by ghost** [cheald/shadowcraft-ui#108]
clicking "Refresh from armory" results in 404-error.

**Comment by timwoj** [comment]
What toon/realm/region? It's possible that the database is missing some piece of gear you have equipped, since I haven't imported anything new from 7.3 yet (I was on vacation for two weeks).

**Comment by DEmonCrypt** [comment]
My main character Rhonyn on EU - Baelgun. I think so too that it's because of some items fom 7.3. My recently upgraded 970 legendary shoulders for example. Not sure though. I tried it later again and then it worked.

**Comment by timwoj** [comment]
I updated the item and relic databases this evening, so it was probably resolved in that.
