### ISSUE TITLE
Got an error while loading my rogue

### ISSUE THREAD

**Issue by clintrough** [cheald/shadowcraft-ui#44]
[Rogue link](http://shadowcraft.mmo-mumble.com/eu/Deathguard/%D0%A0%D0%B5%D0%B7%D1%83%D1%81/)
>Uncaught TypeError: *Cannot read property 'length' of undefined* ah.updateDisplay @ app.js?1435440952:180 ah.boot @ app.js?1435440952:180D._boot @ app.js?1435440952:180D.boot @ app.js?1435440952:180(anonymous function) @ (index):295
app.js?1435440952:180 *Uncaught Invalid dimensions for plot*, width = null, height = null

First one referred to 
 >a7 = Shadowcraft.ServerData.ITEM_BONUSES[a8];
 >for (bA = 0, a0 = a7.length; bA < a0; bA++) {

Second - to 

> if (aj <= 0 || u <= 0) {
>    throw"Invalid dimensions for plot, width = " + aj + ", height = " + u
> }

**Comment by timwoj** [comment]
Looks like the changes made today to help resolve #45 fixed your character not loading.  I'm going to close this for now, but comment if it's still failing in some way and I'll reopen it.

**Comment by clintrough** [comment]
Hey, Tim! Thank you! )

It works fine since that.
