### ISSUE TITLE
Bonus ID system needs major overhaul

### ISSUE THREAD

**Issue by timwoj** [cheald/shadowcraft-ui#45]
The current way we handle bonus IDs on gear is broken beyond belief.  The bonus IDs are stored in a cryptic CSV file with no indication of what the individual fields mean, so adding new IDs is a challenge.  If a piece of gear is found with an ID we're missing, it causes the front end to fail and give a generic error message to the user.

**Comment by cheald** [comment]
Is that CSV extracted from the game files? I know once upon a time we were parsing DBC files to extract data tables from them.

(I haven't touched the code since the advent of the bonus IDs, though, so I may be way off)

**Comment by timwoj** [comment]
I don't know how the original table was generated and I can't find any docs for it anywhere.  The Bonus ID code was originally added for 6.0 though.

**Comment by timwoj** [comment]
Documenting this here so I don't lose it.  I had to regenerate the two tables from the CASC/DBC data from the game using a couple of tools from simc:

Extract the casc files in the game in to DBC files:
./casc_extract.py -m batch -d /Applications/World\ of\ Warcraft -o ~/Desktop/casc

Rename the files so they're how dbc_extract expects:
for i in `ls -1 DB*`; do echo mv $i `echo $i | cut -d '\\' -f 2`; done

Generate the tables (the build number will change):
./dbc_extract.py -b 20182 -t csv --delim=\; -p ~/Desktop/casc ItemBonus > WoD_ItemBonusIDs.csv
./dbc_extract.py -b 20182 -t csv --delim=\; -p ~/Desktop/casc ItemNameDescription > WoD_ItemNameDescription.csv

I'll commit a bunch of comments and documentation related to this later.  There's still the question of how we use the RandPropPoints.csv file since it changed significantly since the last time it was generated.

**Comment by timwoj** [comment]
Merged a big block of changes that clean up the bonus ID system considerably. Closing this now.
