### ISSUE TITLE
Bleeding Hollow Toxin Vessel

### ISSUE THREAD

**Issue by Litvan** [cheald/shadowcraft-ui#61]
I can't pick an upgraded version in the list (valor upgraded).
And in general, an import from armory doesn't reflect any valor upgrades on items currently equipped.

**Comment by WaveFunctionP** [comment]
The upgrades will list in the dropdown menu if you have that option (show upgrades) selected in settings, but most of the upgraded trinkets are not being valued correctly in the drop down ranking and thus show up lower in the list than they should.

AFAIK, upgrades are not in the armory data and thus they will not show when you import your character.

**Comment by timwoj** [comment]
That's correct. The armory is currently not providing upgrade information in the character data, so we have no way to know whether an item has been upgraded or not. There's already a forum post open requesting they fix it, at which time I'll fix ShC to support it.
