### ISSUE TITLE
Dropdown menues settings pane - display issue in Opera

### ISSUE THREAD

**Issue by Trysor** [cheald/shadowcraft-ui#63]
This is with Opera 33.0.1990.115

see screenshot:
https://i.imgur.com/wFy19bp.png

**Comment by timwoj** [comment]
@Trysor This is working fine on the beta site with Opera 37.0.2178.32. Can you retest using that site? http://beta.shadowcraft.mmo-mumble.com.

**Comment by timwoj** [comment]
Closing this because I'm pretty sure it's fixed.

**Comment by Trysor** [comment]
Yes, it is. Thanks!
