### ISSUE TITLE
Mythic Warforged Weapons not importing

### ISSUE THREAD

**Issue by Fierydemise** [cheald/shadowcraft-ui#64]
Character: http://eu.battle.net/wow/en/character/emerald-dream/Sensetive/simple
ShC link: http://shadowcraft.mmo-mumble.com/eu/emerald-dream/sensetive

The weapons do not appear to be importing, likely a missing bonus id.

**Comment by timwoj** [comment]
It is. I need to reload the DB again. I missed some bonus IDs from 6.2.3 related to the MWF items from dungeons.

**Comment by timwoj** [comment]
This was fixed.
